### ISSUE TITLE
Bad Gateway issues with Modrinth

### ISSUE THREAD

**Issue by fxmorin** [Kir-Antipov/mc-publish#10]
Currently, mc-publish fails due to a bad gateway when attempting to publish the mod to Modrinth.
This causes Curseforge to be skipped as well.

https://github.com/fxmorin/carpet-fixes/runs/6843729255?check_suite_focus=true

Edit:
Ok now I'm confused, seems MemoryLeakFix was successful:
https://github.com/fxmorin/MemoryLeakFix/runs/6844070220?check_suite_focus=true
I'll look into it later

**Comment by Kir-Antipov** [comment]
Welp, it's Bad Gateway *(aka HTTP 502, aka server error)*. Sadly, the action cannot publish your assets when there's nothing to publish them to :D That is why `retry-attempts` is a thing - sometimes the only thing you can do is try again later, because Modrinth and CurseForge *(especially, especially CurseForge!)* are not always up.

**Comment by Kir-Antipov** [comment]
> This causes Curseforge to be skipped as well

And this is a good point. Maybe the action shouldn't stop working when only one service is down

**Comment by Geometrically** [comment]
@Kir-Antipov Modrinth was online and normal uploads were working on the site happened. I think mc-publish is causing a server error. There's a bug in our backend when invalid user input could cause a server error.

**Comment by Kir-Antipov** [comment]
@Geometrically, mc-publish got CloudFlare's HTML that reports about HTTP 502 instead of an API response. How in the world a simple request, even if it's maliciously malformed, can cause a bad gateway error? 0_o

**Comment by Kir-Antipov** [comment]
@fxmorin, please, try to republish your assets to Modrinth again later. If it still causes an error, I'll look into it

**Comment by fxmorin** [comment]
I tried multiple times over 2 days, so I'm pretty sure it's not due the site being down

**Comment by Kir-Antipov** [comment]
Forked your repo to test things out, and everything works just fine - https://github.com/Kir-Antipov/carpet-fixes/runs/6845659537

**Comment by Kir-Antipov** [comment]
@Geometrically, how is that server of yours is configured? Maybe action did hit some kind of rate limit during its work?

**Comment by fxmorin** [comment]
well im confused now

**Comment by wafflecoffee** [comment]
> How in the world a simple request, even if it's maliciously malformed, can cause a bad gateway error? 0_o

@Kir-Antipov See actix/actix-web#2695 for more info.

Please reopen this issue -- we're now getting users in Modrinth's support channel reporting this issue, for example https://github.com/DenisD3D/Mc2Discord/runs/7138343984?check_suite_focus=true.

What useragent does mc-publish use? Cloudflare might be blocking it based on the useragent.

**Comment by Kir-Antipov** [comment]
@wafflecoffee,

> we're now getting users in Modrinth's support channel reporting this issue

Well, this is the right thing to do, if you ask me.

> Please reopen this issue

As you [wish](https://github.com/modrinth/labrinth/issues/390) ;)

![image](https://user-images.githubusercontent.com/40232067/177146483-a9742a00-5563-4ab8-b7b0-e70ee03b700d.png)

> What useragent does mc-publish use?

Described all these in the issue

**Comment by Kir-Antipov** [comment]
**⚠️ Note for users that experience this issue**

It may be sufficient for you to temporally downgrade to `Kir-Antipov/mc-publish@v2.1`, it uses Modrinth API v1 that does not seem to have this problem.

**Comment by DenisD3D** [comment]
> **⚠️ Note for users that experience this issue**
> 
> It may be sufficient for you to temporally downgrade to `Kir-Antipov/mc-publish@v2.1`, it uses Modrinth API v1 that does not seem to have this problem.
Hi, 
I'm still getting Bad Gateway error with v2.1 as you can see here: https://github.com/DenisD3D/Mc2Discord/runs/7904933908?check_suite_focus=true (see action here: https://github.com/DenisD3D/Mc2Discord/blob/9df02c87d32e9abac0e3281e328c56b3f568139d/.github/workflows/release.yml#L206-L229)

**Comment by Kir-Antipov** [comment]
@DenisD3D, try revoking your Modrinth token *(don't forget to update it in all affected projects of yours)*, it helped fxmorin to sort their issue out. Also, you can ping Modrinth devs and/or devs of the crate they rely on, which causes this annoying HTTP 502 to be returned instead of something a little bit more descriptive and helpful.

**Comment by wafflecoffee** [comment]
Again, this is something out of our control re actix/actix-web#2695. The only way we can really fix this is to stop using actix, which isn't a practical solution.

**Comment by Kir-Antipov** [comment]
@wafflecoffee, I know, I know. Just passing the problem down the pipeline :)

**Comment by Kir-Antipov** [comment]
As mentioned by wafflecoffe in modrinth/labrinth#390, this should not happen anymore. Modrinth should now return human-readable HTTP 4xx responses on bad input. Therefore, unpinning the issue
