### ISSUE TITLE
[Enhancement] Neoforge since Minecraft 1.20.5 uses "neoforge.mods.toml"

### ISSUE THREAD

**Issue by shartte** [Kir-Antipov/mc-publish#118]
### Current Behavior

Neoforge has changed the name for mods.toml, leading to some values (such as game version) no longer being read automatically.

### Desired Behavior

Support for neoforge.mods.toml (same format as mods.toml, still)

**Comment by Kir-Antipov** [comment]
Thanks for the notice! Just to make sure, the metadata file still resides in the `META-INF` directory, making its full path `META-INF/neoforge.mods.toml`, right?

**Comment by cech12** [comment]
https://neoforged.net/news/20.5release/

Here is the official post of this change.

**Comment by Kir-Antipov** [comment]
Got it, thanks!

**Comment by Kira-NT** [comment]
Once again, thanks a lot for informing me about this important matter! A fixup has been applied to the current "rolling release" - v3.3, so no actions are needed from the users to continue uploading their NeoForge mods with ease :)
