### ISSUE TITLE
publishing order

### ISSUE THREAD

**Issue by DAmNRelentless** [Kir-Antipov/mc-publish#16]
Maybe a bit of an odd request but would it be possible to change the publishing order of the action?
I know I could make different steps by using the action multiple times but since CurseForge is down **considerably more often** than Modrinth, I'd like the action to try to publish to CF first so if that fails, the whole action fails and the release is canceled.

**Comment by DAmNRelentless** [comment]
I would be more than happy with the new default order.
And if you want to make it a configurable option, I see the problem. The order would need to be defined in a list or an array of strings. I doubt the order of the config keys is the same within the workflow, otherwise, another approach would be taking the order of the tokens in the config.

So if you have:
```
mr_token: asdf
cf_token: asdf
github_token: asdf
```
it would use this publishing order.

**Comment by Kir-Antipov** [comment]
> I would be more than happy with the new default order

The goal of this project is to be as zero-configy as possible, therefore, everything that makes sense to a lot of people will be converted into a feature here :)

> I doubt the order of the config keys is the same within the workflow

Yep, that is the problem. GitHub actually converts all inputs to environment variables (e.g., `name` transforms into `INPUT_NAME`). And, to put it mildly, I am not sure that `process.env` respects the order of declaration of those variables

**Comment by DAmNRelentless** [comment]
Hmm, I have no other idea then. The new default order would be fine I guess and if someone really wants to do it differently, they need to use multiple steps I guess.

**Comment by Kir-Antipov** [comment]
Yeah, makes sense. Let's keep it this way
