### ISSUE TITLE
If no token for Curse, Modrinth or GitHub is present, the action still tries to publish

### ISSUE THREAD

**Issue by NoComment1105** [Kir-Antipov/mc-publish#2]
The documentation in hte GitHub readme clearly states [here](https://github.com/Kir-Antipov/mc-publish/blob/master/README.md#L83-L95) that to not publish to one of the mod distribution sites, all you have to do is omit that section from your buildscript. However this is incorrect, since the action will still try to publish even if the token is not there.
An example is listed below:
![image](https://user-images.githubusercontent.com/67918617/145226761-e66c4f6d-b55f-4308-b46e-aec526f0b911.png)
As you can see in the image there is clearly no GitHub token being specified, yet a publishing attempt is still made.

**Comment by Kir-Antipov** [comment]
Thank you for reporting this one. It seems that there are some other environment variables which start with `GITHUB`
