### ISSUE TITLE
Fabric version detection

### ISSUE THREAD

**Issue by DrexHD** [Kir-Antipov/mc-publish#36]
I just ran into a problem where mc-publish could not auto-detect supported versions of my mod from my [fabric.mod.json](https://github.com/DrexHD/AntiXray/blob/1.19.x/stable/fabric/src/main/resources/fabric.mod.json#L35) file. 

I am using an array of version ranges to specify the supported versions, which is allowed according to the [specifications](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec).
```json
"minecraft": [
  "1.19.1",
  "1.19.2"
]
```
The failed [Workflow](https://github.com/DrexHD/AntiXray/runs/8258987744?check_suite_focus=true#step:10:87) and the error: `Error: At least one game version should be specified`

**Comment by Kir-Antipov** [comment]
`v4.0` will be focused on huge improvements of the version range detection mechanics, so thank you for mentioning this, because I somehow managed to miss the fact that Fabric allows arrays in this context
