### ISSUE TITLE
Don't unfeature Modrinth versions if the new upload doesn't succeed

### ISSUE THREAD

**Issue by Madis0** [Kir-Antipov/mc-publish#37]
I run mc-publish with GitHub releases and I intentionally made a release that did not contain a valid Modrinth modpack file. However, the script still unfeatured the latest version of the modpack on Modrinth, even though the new upload failed.

I suggest doing the unfeature only if the new upload succeeds.

![image](https://user-images.githubusercontent.com/8611110/189949137-c8fc9f36-cb2b-4bd6-8765-9c1c86752880.png)

**Comment by Kir-Antipov** [comment]
Yep, makes sense

**Comment by srnyx** [comment]
> I run mc-publish with GitHub releases and I intentionally made a release that did not contain a valid Modrinth modpack file.

Completely unrelated; so this works with modpacks too (I don't think the [README](https://github.com/Kir-Antipov/mc-publish/blob/master/README.md) says this anywhere)? If so, could you add some information about how to set it up for a modpack in the [README](https://github.com/Kir-Antipov/mc-publish/blob/master/README.md), @Kir-Antipov?

**Comment by Madis0** [comment]
Considering I haven't actually gotten it to work yet, I cannot confirm it works with modpacks 😆

**Comment by Kir-Antipov** [comment]
> Completely unrelated; so this works with modpacks too?

I don't see why it should not. Yes, `mc-publish` does not support Modrinth's `.mrpack` *[yet]*, but this fact only means that you should provide all the related information by yourself, it does not affect that part of the project which is just a wrapper over Labrinth API

> If so, could you add some information about how to set it up for a modpack in the README

I tend to document only fully supported features, e.g., "target-specific" properties were here from the very beginning, but they finally made their way to README only when I refined them and made them more user-friendly

**Comment by Kir-Antipov** [comment]
Fixed in [v3.3](https://github.com/Kir-Antipov/mc-publish/releases/tag/v3.3).
