### ISSUE TITLE
Modrinth unfeature release type subset

### ISSUE THREAD

**Issue by DevScyu** [Kir-Antipov/mc-publish#41]
As title says, it would be nice to only unfeature versions of the same release type as we are uploading, so it can show latest beta and stable versions.

**Comment by Kir-Antipov** [comment]
Agree, will make this aspect configurable too

**Comment by Kir-Antipov** [comment]
Implemented in [v3.3](https://github.com/Kir-Antipov/mc-publish/releases/tag/v3.3).
