### ISSUE TITLE
`files-secondary` is ignored without `files-primary` being present

### ISSUE THREAD

**Issue by ginsm** [Kir-Antipov/mc-publish#47]
Howdy, how would you go about disabling `files-secondary` entirely? I only want it to upload the main file and nothing else.

I tried `build/libs/!*` but it seemed to ignore it (I'm guessing that's an invalid glob pattern?).

Thanks and awesome project! :)

**Comment by ginsm** [comment]
Awesome, thanks :)

**Comment by Kir-Antipov** [comment]
The issue is no longer relevant for [v3.3+](https://github.com/Kir-Antipov/mc-publish/releases/tag/v3.3).
