### ISSUE TITLE
Support Quilt Loader

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Kir-Antipov/mc-publish#5]
Modrinth supports the quilt loader, and curseforge plans to. With Quilt mods, you can check for `src/main/resources/quilt.mod.json`.

**Comment by Faboslav** [comment]
Hello there, is there any update? This would be really nice at least for the modrinth.

**Comment by Kir-Antipov** [comment]
Not really. I'm not that active during the war. But Quilt support will be implemented, don't worry

**Comment by Faboslav** [comment]
Just for info targeting quilt platforms on both curseforge/modrinth works as expected.

**Comment by Kir-Antipov** [comment]
It would be nice if somebody could provide me with an example of Quilt's mod.json with all available dependency types and custom fields, if any

**Comment by NebelNidas** [comment]
The official specification is here: https://github.com/QuiltMC/rfcs/blob/master/specification/0002-quilt.mod.json.md

**Comment by Kir-Antipov** [comment]
So, there's no "custom" field like in fabric.mod.json? How does the mod loader treat unknown entries? Does it just ignore them?

**Comment by Kir-Antipov** [comment]
Gotcha, thanks!
