### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Asguho** [Kir-Antipov/mc-publish#50]
I get an error message that says the following:
![image](https://user-images.githubusercontent.com/78410939/218745001-50cf7863-492b-4a05-a023-0ee11d961bea.png)
but i am not uploading to github:
![image](https://user-images.githubusercontent.com/78410939/218745097-6b0cc2d1-9ce5-44b1-a62a-b5491d12f737.png)
Anyway i can see the actual error?

**Comment by Kir-Antipov** [comment]
You got great timing :)
Yep, you don't upload to GitHub, but you do upload to Modrinth, which uses GitHub OAuth2 under the hood to authorize its users.

Please, look at the pinned #49 to learn more about this problem. In case you have more questions - you may ask them there!

**Comment by Asguho** [comment]
ohh, that makes sense. Thanks for the quick response
