### ISSUE TITLE
Multi-project builds

### ISSUE THREAD

**Issue by Epic428** [Kir-Antipov/mc-publish#53]
Not sure if there's support built-in or planned, but it would be nice to support multi-project builds such as Architectury. I assume I could abuse the `secondary-files` field and have both fabric and forge. This solution doesn't take into account devs who might do forge/fabric/quilt in one.

**Comment by Kir-Antipov** [comment]
Please, check out this discussion - ["What would be the ideal setup for my multi-platform project?"](https://github.com/Kir-Antipov/mc-publish/discussions/29), and let me know if you found what you wanted there.

**Comment by Kir-Antipov** [comment]
I'm gonna assume that you did.
