### ISSUE TITLE
Add outputs to the action

### ISSUE THREAD

**Issue by the456gamer** [Kir-Antipov/mc-publish#54]
for example modrinth, which exposes the new version id in its api, which i would use to get the url for the release page
https://modrinth.com/mod/{projid}/versions/{versionid}

my use is providing a pretty summary of the locations its published (in my own format)

**Comment by Kir-Antipov** [comment]
What would be the name of such output?

**Comment by Kir-Antipov** [comment]
> https://docs.curseforge.com/#get-mod

This is the so-called "Eternal API", which has nothing to do with CurseForge Upload API. So, yep, you need a different API key for that *(which you need to [apply for](https://forms.monday.com/forms/dce5ccb7afda9a1c21dab1a1aa1d84eb?r=use1), it seems 🤡)*. Therefore, cannot be used to solve the issue we have here.

**Comment by Kir-Antipov** [comment]
Implemented in [v3.3](https://github.com/Kir-Antipov/mc-publish/releases/tag/v3.3).
