### ISSUE TITLE
 Error: FetchError: Cannot follow redirect with body being a readable stream

### ISSUE THREAD

**Issue by Steveplays28** [Kir-Antipov/mc-publish#61]
Not sure what's going wrong here, just configured the plugin like in the examples, but it's failing at uploading to CurseForge.
Don't mind the `github-tag` not quite working, still setting that up.

Here's the [workflow `.yml` file](https://github.com/Steveplays28/restart-server/blob/main/.github/workflows/publish.yml).

![error_mc_publish](https://user-images.githubusercontent.com/62797992/233808222-58a4d225-f796-4a84-8e87-a6f3e51acfa7.png)

<details>
<summary>Log</summary>

Run Kir-Antipov/mc-publish@v3.2
  with:
    github-token: ***
    modrinth-id: $MODRINTH_ID
    modrinth-token: ***
    curseforge-id: $CURSEFORGE_ID
    curseforge-token: ***
    github-tag: v+mc1.19.x
    files: build/libs/!(*-@(dev|sources|all)).jar
    version-type: release
    modrinth-featured: false
    modrinth-unfeature-mode: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    files-primary: ${undefined}
    files-secondary: ${undefined}
    name: ${undefined}
    version: ${undefined}
    changelog: ${undefined}
    changelog-file: ${undefined}
    loaders: ${undefined}
    game-versions: ${undefined}
    dependencies: ${undefined}
    version-resolver: ${undefined}
    java: ${undefined}
    retry-attempts: 2
    retry-delay: 10000
    fail-mode: ${undefined}
    modrinth-files: ${undefined}
    modrinth-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    modrinth-version: ${undefined}
    modrinth-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    modrinth-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-files: ${undefined}
    curseforge-files-primary: ${undefined}
    curseforge-files-secondary: ${undefined}
    curseforge-name: ${undefined}
    curseforge-version: ${undefined}
    curseforge-version-type: ${undefined}
    curseforge-changelog: ${undefined}
    curseforge-changelog-file: ${undefined}
    curseforge-loaders: ${undefined}
    curseforge-game-versions: ${undefined}
    curseforge-dependencies: ${undefined}
    curseforge-version-resolver: ${undefined}
    curseforge-java: ${undefined}
    curseforge-retry-attempts: ${undefined}
    curseforge-retry-delay: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-files: ${undefined}
    github-files-primary: ${undefined}
    github-files-secondary: ${undefined}
    github-name: ${undefined}
    github-version: ${undefined}
    github-version-type: ${undefined}
    github-changelog: ${undefined}
    github-changelog-file: ${undefined}
    github-loaders: ${undefined}
    github-game-versions: ${undefined}
    github-dependencies: ${undefined}
    github-version-resolver: ${undefined}
    github-java: ${undefined}
    github-retry-attempts: ${undefined}
    github-retry-delay: ${undefined}
    github-fail-mode: ${undefined}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.6-10/x64
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
  
📤 Publishing assets to CurseForge...
Error: FetchError: Cannot follow redirect with body being a readable stream

</details>

**Comment by Steveplays28** [comment]
This one's my own fault, didn't specify the CurseForge project ID properly.

**Comment by Kir-Antipov** [comment]
Oh, don't tell me CurseForge redirects you somewhere if the ID is invalid...

Yup, I checked it. CurseForge redirects an API call to their generic 404 HTML page. Beautiful. How did we let a company, which manages to fail at every step of developing a concise API, become the largest distributor of our mods?

I will need to wrap this error in something more user-friendly, so thank you for letting me know!

**Comment by Steveplays28** [comment]
Yup, indeed. CurseForge moment.
Wrapping the error into something more user-friendly would be amazing, thanks!
