### ISSUE TITLE
Add an option to supply a markdown file to set as a description

### ISSUE THREAD

**Issue by meza** [Kir-Antipov/mc-publish#75]
Would be fantastic to be able to supply the mod's README.md as a source of truth for the descriptions of the mods.
Is that something that could be done?

**Comment by Kir-Antipov** [comment]
Thank you for your suggestion! If I understand it correctly, somebody did suggest such thing earlier in #19. Sadly, nothing has improved on CurseForge's *(a.k.a. the main gatekeeper of this issue)* side since then. Please, check out the old issue and let me know if it answers your question!

**Comment by meza** [comment]
Thanks, it is the same thing.
