### ISSUE TITLE
1.8.1 isn't selected for CurseForge

### ISSUE THREAD

**Issue by srnyx** [Kir-Antipov/mc-publish#81]
```yml
game-versions: ">=1.8.8"
game-version-filter: releases
```
File published: https://dev.bukkit.org/projects/annoying-api/files/4646459
1.8.1 is the only version not selected

**Comment by Kir-Antipov** [comment]
Honestly, your issue isn't entirely clear to me. I would greatly benefit from a more detailed explanation of the problem you're experiencing. Also, just to note, the URL you've included seems to lead to a 404 page.

As for your configuration, it produces the following set of suitable CurseForge version IDs:

```jsonc
[
  // Bukkit Plugins
  [
    9994, 9974, 9973, 9561,
    9560, 9261, 9190, 9016,
    8897, 8849, 8503, 7915,
    7667, 7330, 7105, 6588,
    630,  591,  585,  531,
  ],

  // Modpacks, Customization, Resource Packs, and Worlds
  [
    9990, 9971, 9776, 9550, 9366, 9259,
    9186, 9008, 8857, 8830, 8516, 8152,
    8203, 8134, 8056, 8010, 7892, 7890,
    7722, 7675, 7664, 7469, 7413, 7361,
    7344, 7318, 7132, 7107, 7081, 6756,
    6711, 6580, 6452, 6451, 6317, 6170,
    6160, 6144, 6084, 6085, 5997, 5998,
    5946, 5806, 5703,
  ],

  // Addons
  [
    9993, 9970, 9792, 9552,
    9551, 9260, 9189, 8899,
    8504, 7997, 7996, 7436,
    7435, 7434, 7433, 7432,
    7431, 7430,
  ],
]
```

Obviously, we are particularly interested in the "Bukkit" section. So, the versions being used in your case are these ones:

```jsonc
[
  9994, // 1.20.1
  9974, // 1.20
  9973, // 1.19.4
  9561, // 1.19.3
  9560, // 1.19.2
  9261, // 1.19.1
  9190, // 1.19
  9016, // 1.18.2
  8897, // 1.18.1
  8849, // 1.18
  8503, // 1.17
  7915, // 1.16
  7667, // 1.15
  7330, // 1.14
  7105, // 1.13
  6588, // 1.12
  630,  // 1.11
  591,  // 1.10
  585,  // 1.9
  531,  // 1.8
]
```

The output seems normal to me given your game version constraint. Without a clear understanding of your concerns or the exact issue you're facing, it's challenging to provide a more specific answer. Therefore, I'd kindly request you to elaborate on the problem you're experiencing, providing as much detail as possible.

**Comment by srnyx** [comment]
> Also, just to note, the URL you've included seems to lead to a 404 page.

Sorry, I had deleted that version, here's a new one: https://dev.bukkit.org/projects/annoying-api/files/4646474

> The output seems normal to me given your game version constraint.

It's missing 1.8.1:
![image](https://github.com/Kir-Antipov/mc-publish/assets/25808801/31a9d312-ce51-4577-9af3-786a53f6d6eb)
