### ISSUE TITLE
Modrinth JSON parsing error

### ISSUE THREAD

**Issue by srnyx** [Kir-Antipov/mc-publish#87]
```
📤 Uploading assets to CurseForge
✅ Successfully published assets to CurseForge in 3105 ms
📤 Uploading assets to Modrinth
Error: HttpError: 400 (Bad Request, {"error":"invalid_input","description":"Error while parsing JSON: missing field `version_number` at line 1 column 569"})
```
https://github.com/srnyx/midas-touch/blob/master/.github/workflows/publish.yml
https://github.com/srnyx/tools/blob/main/.github/workflows/publish.yml

**Comment by srnyx** [comment]
Think this was cause I manually called the workflow instead of having a new release trigger it

**Comment by Kir-Antipov** [comment]
Since `mc-publish` versions <4.0 cannot read the metadata of plugins, without a `GITHUB_REF` environment variable being set or a version being manually specified, there's no way to infer that value.

I'm going to reopen this issue because the error message is confusing for the end user.
