### ISSUE TITLE
Why the version uploaded only the last one

### ISSUE THREAD

**Issue by SettingDust** [Kir-Antipov/mc-publish#97]
![图片](https://github.com/Kir-Antipov/mc-publish/assets/19922286/1b61bc1f-2fbb-404b-a0ed-c080b0cc96c6)
https://github.com/SettingDust/ModSets/blob/main/.github/workflows/publish.yml#L57-L60

**Comment by Kir-Antipov** [comment]
Please, specify the `game-version-filter` input if you want to override the default behavior game version resolution:

```yaml
game-version-filter: releases
```
